name: Gradle build and test
on:
  pull_request:
    branches:
      - main
jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Create jar for integration test
        working-directory: ./connect-extension
        run: ./gradlew shadowJar

      - name: Run tests
        working-directory: ./connect-extension
        run: ./gradlew test --info
