name: Publish artifact to github packages
on:
  release:
    types: [ created ]
jobs:

  publish-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Publish artifact
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
        working-directory: ./connect-extension
        # The GITHUB_REF tag is in the format 'refs/tags/xxx'.
        run: |
          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "New version: ${NEW_VERSION}"
          ./gradlew -Pversion=${NEW_VERSION} publish
