on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Create release artifact
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
        working-directory: ./connect-extension
        # The GITHUB_REF tag is in the format 'refs/tags/xxx'.
        run: |
          export VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "New version: ${VERSION}"
          ./gradlew shadowJar

      - name: Create checksums
        working-directory: connect-extension/build/libs/
        shell: bash
        run: for f in *.{jar,zip}; do sha512sum $i > $i.sha512; done

      - name: create gh release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "connect-extension/build/libs/*.zip,connect-extension/build/libs/*.jar,connect-extension/build/libs/*.sha512"
          makeLatest: true
